blueprints/common.py
import os
from flask import Blueprint, render_template, abort, url_for, redirect, session
from jinja2 import TemplateNotFound
from auth import del_user

common = Blueprint('common', __name__,
                        template_folder='templates',
                        static_folder='static')


@common.route('/')
def index():
    return render_template('index.html')


@common.route('/logout')
def logout():
    del_user()
    return redirect(url_for('common.index'))


@common.route('/ok')
def status_api():
    # ELB health check endpoint - not logged in nginx or uwsgi
    return 'OK'


@common.route('/favicon.ico')
def favicon():
    return redirect(url_for('static', filename='favicon.ico'))


@common.route('/terms')
def terms():
    return render_template('terms.html')
  
@common.route('/privacy-policy')
def privacy():
    return render_template('privacy.html')

templates/layout_terms.html
<!doctype html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
<title>{% block title %}Welcome{% endblock %} - Meraki Social Splash</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  <main id="main" class="site-main" role="main">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $(".section.hide").first().load("https://splash.getlocalmeasure.com/assets/{{ session.asset_path }}/terms.html", function() {
        $(this).show();
      });
    });
  </script>
{% for message in get_flashed_messages() %}
  <p class=message>{{ message }}</p>
{% endfor %}
    <div class="content--narrow" >
{% block body %}{% endblock %}
    </div>
  </main>
</body>
</html>

templates/meraki-success.html
{% extends "layout.html" %}
{% block body %}
<section class="section">
  <div class="content--narrow white">
    <h2>Welcome!</h2>
    <div class="block">
      <div class="block-header">
        <div class="block-header-icon--large">
          <img class="avatar" src="{{ session.avatar }}" alt="">
        </div>
        <h3 class="block-heading">{{ session.name }}
          <span class="subhead">{{ session.username }}</span>
        </h3>
      </div>
      <p><a class="button--light" href="{{ url_for('common.logout') }}">Logout</a></p>
    </div>
  </div>
 </section>

{% endblock %}